# Generated by Django 4.1.5 on 2023-02-02 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dresscategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='DressLists')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dresscategory')),
            ],
        ),
    ]
