# Generated by Django 4.1.5 on 2023-02-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
